name: "📝 选题申请：推荐一篇新论文"
description: "如果您想复现一篇新论文，请通过此模板提交申请"
title: "[选题申请] <请在此填写论文标题>"
labels: ["Phase-1: Selection"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您参与Lab4AI论文复现！在提交前，请确保您已仔细阅读并下载了 **[贡献者工具包](https://github.com/Lab4AI-Hub/PaperHub/tree/main/contributor-kit)**。
        
        **下一步**：请下载工具包中的 `2-选题阶段-论文筛选表.xlsx`，填写完整后，直接**拖拽到下方**的文本框中以上传附件。
  - type: textarea
    id: comments
    attributes:
      label: "补充说明 (可选)"
      description: "关于这篇论文，您还有什么想补充说明的吗？"
