name: "✅ 成果提交：申请项目上架"
description: "当您完成论文复现后，请通过此模板提交最终成果"
title: "[成果提交] <论文标题> by @<你的GitHub用户名>"
labels: ["Phase-2: Submission"]
body:
  - type: markdown
    attributes:
      value: |
        太棒了！恭喜您完成了复现工作！
        
        **下一步**：请下载 **[贡献者工具包](https://github.com/Lab4AI-Hub/PaperHub/tree/main/contributor-kit)** 中的 `3-成果提交-项目上架表.xlsx`，填写完整后，**拖拽到下方**的文本框中以上传附件。
  - type: input
    id: project-url
    attributes:
      label: "您在Lab4AI平台的项目链接"
      description: "请提供您个人账号下，已完成复现的项目的公开链接。"
      placeholder: "https://www.lab4ai.cn/user/yourname/project/xxx"
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: "复现心得与总结 (可选)"
      description: "可以分享一下您的复现过程、遇到的挑战或任何想对社区说的话。"
