# sync-to-gitee.yml (全新终极版)

name: Sync to Gitee

on:
  push:
    branches:
      - main # 确保这是您的主分支名

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Mirror to Gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.GITEE_REPO_URL }}
          ssh_private_key: # 这个名字虽然叫 ssh_private_key，但我们实际上会传入一个空值，因为我们不用它了
            false
